### ISSUE TITLE
[Feature]: Installer for Ubuntu 24.04

### ISSUE THREAD

**Issue by maartenarnst** [ROCm/rocprofiler-systems#11]
### Suggestion Description

The (omnitrace) assets are currently missing installers for Ubuntu 24.04. Even though other pieces of ROCm, such as the Docker images, are now available with Ubuntu 24.04. More generally, it would be great to always have an installer for the latest supported software version, such as currently Ubuntu 24.04 with ROCm 6.2. This feature suggestion is thus a suggestion to include the installer for Ubuntu 24.04.

### Operating System

Ubuntu

### GPU

MI250X, Radeon VII Pro

### ROCm Component

omnitrace/rocprofiler-systems

**Comment by dgaliffiAMD** [comment]
We ran into some build issues with Omnitrace on Ubuntu 24.04 due to an outdated PAPI module. That has been resolved with https://github.com/ROCm/rocprofiler-systems/commit/c11abc4ea169b75c7d8021d13e87e45cdbec8eb0 and ROCm 6.3's `rocprofiler-systems` package will have support for Ubuntu 24.04.
