### ISSUE TITLE
[Documentation]: Documentation is inaccessible behind authentication

### ISSUE THREAD

**Issue by GMNGeoffrey** [ROCm/rocprofiler-systems#47]
### Description of errors

Following the documentation link from the README (https://rocm.docs.amd.com/projects/rocprofiler-systems/en/latest/index.html) leads to a readthedocs page that asks you to log in.

![image](https://github.com/user-attachments/assets/8a74ecd8-f14f-437f-b79a-aeef008525da)

That's already weird, but even if I log in using my Google account (I looked at GitHub SSO but Read the Docs wanted way more access than seemed reasonable) I get an unauthorized message:

![image](https://github.com/user-attachments/assets/d4c017f0-cdaa-4696-91e6-be56e60ec77b)

**Comment by GMNGeoffrey** [comment]
Maybe this is related to renaming from omnitrace and it's unhelpfully prompting login rather than serving a 404? I found omnitrace documentation here: https://rocm.docs.amd.com/projects/omnitrace/en/latest/index.html. Regardless, please fix the README so it points to correct, accessible documentation

**Comment by harkgill-amd** [comment]
Hi @GMNGeoffrey, apologies for the inconvenience. The rocprofiler-systems page will go live in the next couple days in which case you will no longer be redirected to ReadTheDocs. In the meantime, please continue to use the Omnitrace documentation. Will leave this issue open until the page goes live, thanks!

**Comment by harkgill-amd** [comment]
@GMNGeoffrey, the page is now live and the link no longer redirects to RTD.

**Comment by GMNGeoffrey** [comment]
Excellent, thank you :-)
