### ISSUE TITLE
[Issue]: rocprofiler-systems installer missing for rocm 6.3

### ISSUE THREAD

**Issue by maartenarnst** [ROCm/rocprofiler-systems#49]
### Problem Description

The `rocprofiler-systems` install script for rocm 6.3 is missing in the `rocm-6.3` release.

It appears the issue may be that the workflow is still configured so as to create an install script for rocm 6.2:

- https://github.com/ROCm/rocprofiler-systems/blob/8f0282bb691fd1286fdc90ab3e6823ad86415f86/.github/workflows/ubuntu-jammy.yml#L78

### Operating System

ubuntu 22.04

### CPU

AMD Ryzen 5950X

### GPU

Radeon Pro VII

### ROCm Version

ROCm 6.2.0

### ROCm Component

rocprofiler

### Steps to Reproduce

E.g., taking the docker image `rocm/dev-ubuntu-22.04:6.3` and running

```
apt update
apt install wget
wget https://github.com/ROCm/rocprofiler-systems/releases/latest/download/rocprofiler-systems-install.py
python3 ./rocprofiler-systems-install.py --prefix /opt/rocprofiler-systems --rocm 6.3
```

leads to the error message:

```
No such file or directory: '/tmp/rocprof-sys-install-zpmjdsox/rocprofiler-systems-0.1.0-ubuntu-22.04-ROCm-60300-PAPI-OMPT-Python3.sh'
```

**Comment by ppanchad-amd** [comment]
Hi @maartenarnst. Internal ticket has been created to investigate your issue. Thanks!

**Comment by dgaliffiAMD** [comment]
Thanks @maartenarnst . 
We have a bit of a "chicken-and-egg" problem, since the workflow depends on the public release of rocm-6.3. We're working on updating the installers
In the meantime, you can install "rocprofiler-systems" packaged with rocm-6.3 by following the installation [quick start]( https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html) and then running "apt install rocprofiler-systems".

**Comment by maartenarnst** [comment]
Hi @dgaliffiAMD Ok! That’s great that it is now packaged! I’ll try and report back.

**Comment by maartenarnst** [comment]
Hi @dgaliffiAMD. It may be worth doublechecking this line too:

- https://github.com/ROCm/rocprofiler-systems/blob/8f0282bb691fd1286fdc90ab3e6823ad86415f86/cmake/Templates/rocprof-sys-install.py.in#L235

because it looks like rocprofiler-systems is currently not (yet?) working with release version tags that start with "v".

**Comment by dgaliffiAMD** [comment]
Hi, 
I have manually uploaded the rocm-6.3 installers and updated the installer script to handle the "rocm-X.Y.Z"-style tags. Thank you for pointing that one out. :)

**Comment by maartenarnst** [comment]
Hi @dgaliffiAMD. OK. Thanks a lot for the manual upload and for the PR. I confirm that things now work on our side, both on `ubuntu 22.04` and on `ubuntu 24.04`.
